project_identifier: nononsensenotes
api_key: ec4eea55d5bd72abace6c48779460835
base_url: http://api.crowdin.com
#base_url: https://api.crowdin.com/api/project/
base_path: /home/jonas/workspace/NotePad/app

files:
  -
    source: '/src/main/res/values/strings.xml'
    translation: '/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping:
      android_code:
        # we need this mapping since Crowdin expects directories
        # to be named like "values-uk-rUA"
        # acording to specification instead of just "uk"
        zh-rTW: zh-rTW
        zh-rCN: zh-rCN
        pt-rBR: pt-rBR
        fi-rFI: fi-rFI
